apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e66xkn4ma-python 
  janus-idp.io/tekton: e66xkn4ma-python
  backstage.io/kubernetes-id: e66xkn4ma-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e66xkn4ma-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml